### ISSUE TITLE
不会使用 GitHub Page

### ISSUE THREAD

**Issue by Cxl-Xc** [hzpt-inet-club/inet.org#26]
我从官网上fork了inet  但是我github pages了之后 生成的网页 进去之后就没样式了 是怎么回事

**Comment by Cxl-Xc** [comment]
我从官网上fork了inet 但是我github pages了之后 生成的网页 进去之后就没样式了 是怎么回事

**Comment by hzpt-inet** [comment]
## 原因
因为 GitHub Page 选择的分支不正确，我们可以发现在「.github/workflows」目录中有一个 work.yml 文件，他就是自动部署的脚本，在第52行，可以发现它会自动部署『gh-pages』分支，这才是该项目的最终展示分支。

## 解决方法
1. 进入 setting 选项卡
2. 选择 page 标签
3. 设置 Source 分支为 gh-pages
4. 点击save

> 我这么描述你可以听明白吗？

**Comment by hzpt-inet** [comment]
当然，我们需要提前约定一下
1. 先阅读 #6 该issue描述了该项目的起因，和一些善意的规则。
2. 然后在阅读 #4 该issue描述了该项目必须遵守的规则。
3. 有任何的疑问提出 issue，由任何拿捏不住的可以开启 discussions
4. issue和pr以及discussions的标题和内容可以使用中文。
5. 提交contributions的时候可以在结束时使用`()`使用中文描述。
    例如：`docs: update docs (我做了什么)`

> 善意的提醒：希望你们可以快速的在 #15 中领取任务，并且在 #23 完成自己的个人介绍，十分感谢

**Comment by Cxl-Xc** [comment]
谢谢 成功解决了
