### ISSUE TITLE
如何使css样式只影响一个md

### ISSUE THREAD

**Issue by Cxl-Xc** [hzpt-inet-club/inet.org#29]
我在md里写入css样式 但是所有的md全部都被影响了 如何只影响一个md文件

**Comment by hzpt-inet** [comment]
这是需要组件的使用才能不影响全部的 markdown 文件，需要在组件库中创建一个 「组件 components」并且使用 vue3 + ts 就可以使用css样式，并且只影响需要引入的 markdown 。
