### ISSUE TITLE
修复

### ISSUE THREAD

**Issue by 011011100** [hzpt-inet-club/inet.org#7]
修复：2020Team.md中出现的名字错误
文件：2020Team.md
- [历卓翰]  ---> -[厉卓翰]

**Comment by xiaoxunyao** [comment]
啊！🤔这应该是一个失误，因为你们的信息现在不应该单独出现一个 `markdown` 文件，我想这一定是一个善意的错误！

**Comment by hzpt-inet** [comment]
@011011100 您可以检查新的版本，确认没有任何问题之后，麻烦您将此issue关闭，十分感谢您对于「INet」社区所作出的贡献！
