### ISSUE TITLE
修复文件的错误

### ISSUE THREAD

**Issue by xiaoxunyao** [hzpt-inet-club/inet.org#9]
## 问题描述

应该是 @dai147444612 不小心创建了一个本属于「src/team/README.md」的内容多创建了一个 「2020Team.md」文件，导致了 @011011100  的真实姓名的错误，我想这应该是一个无心之举，需要快速的解决！

## 解决方案

目前的解决方案是
- [x] 删除 「src/team/2020Team.md」文件

**Comment by hzpt-inet** [comment]
接受了所对应的PR所以将此issue关闭！如有任何不满意的地方可以再次打开此issue
